### ISSUE TITLE
Test coverage is at 0%

### ISSUE THREAD

**Issue by carnesen** [bitpay/bitcoind-rpc#13]
https://coveralls.io/builds/3150724

[![Coverage Status](https://img.shields.io/coveralls/bitpay/bitcoind-rpc.svg?style=flat-square)](https://coveralls.io/r/bitpay/bitcoind-rpc?branch=master)

**Comment by braydonf** [comment]
Coveralls integration hasn't been working well lately, any ideas?

**Comment by braydonf** [comment]
Working again
