### ISSUE TITLE
Has this repo been abandoned?

### ISSUE THREAD

**Issue by carnesen** [bitpay/bitcoind-rpc#28]
Hello BitPay, Repo Watchers,

It's been 14 months since the last commit was merged to master on this repo. Even trivial PRs like #26 have not been merged. Am I correct in stating that this repo has been abandoned by its original maintainers? If so, could I take over maintenance of this project? By way of background, I'm a professional full-stack JavaScript software engineer and long-time bitcoiner. I've attached my resume to this comment. I'm very familiar with bitcoind's RPC interface. In addition to writing my own Node.js library (long since abandoned), I (re)wrote the description of the interface on bitcoin.org https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs https://github.com/bitcoin-dot-org/bitcoin.org/pull/1030
[Chris_Arnesen.pdf](https://github.com/bitpay/bitcoind-rpc/files/1515099/Chris_Arnesen.pdf)

Regards,
Chris Arnesen

**Comment by patricknee** [comment]
i would appreciate your contribution!

**Comment by carnesen** [comment]
@patricknee Thanks for the response. Could/will you make me a committer on this repo and the npm package?

**Comment by patricknee** [comment]
Sorry, I'm not able to. This was more of a +1 vote.

**Comment by carnesen** [comment]
Update: As per https://docs.npmjs.com/misc/disputes, I emailed the owners of the bitcoind-rpc package and requested to be added as a collaborator.

> Hello Braydon, Gabe, Stephen, Patrick,
>
> I'm emailing you as the "collaborators" on the npm package bitcoind-rpc. I'm a watcher on that package's GitHub repository and noticed that pull requests and issues submitted by the community aren't receiving any response. See for example, https://github.com/bitpay/bitcoind-rpc/pull/26 or https://github.com/bitpay/bitcoind-rpc/pull/27 . In fact it's been 14 months since the last commit was merged to the "master" branch there, corresponding to the last time a new version of the bitcoind-rpc package was published to the npm registry. As you know, the Bitcoin server software is rapidly evolving with new RPC calls being added all the time. Unfortunately the bitcoind-rpc package isn't keeping pace with that evolution. I'd like to help you bring bitcoind-rpc up to date and keep it that way. Would you be willing to add me (carnesen) as a collaborator? The command is:
>
> npm owner add carnesen bitcoind-rpc
>
> Of course to be effective, I'd also need to be made a maintainer on the underlying GitHub repository https://github.com/bitpay/bitcoind-rpc . Alternatively if BitPay no longer wishes to maintain that repository under its organization, we could create a new GitHub organization for this purpose or fork the repository to my GitHub user namespace, carnesen.
>
> I also sent a message similar to this one through the "issues" page on GitHub, though I didn't receive any response beyond a "+1" from a member of the community. https://github.com/bitpay/bitcoind-rpc/issues/28
>
>I've attached my resume to this email. Here I am on LinkedIn. I'm very familiar with Node.js, npm, and bitcoind's RPC interface. In addition to writing my own similar library (long since abandoned), I (re)wrote the description of the interface on bitcoin.org https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs bitcoin-dot-org/bitcoin.org#1030 . 
>
>Best regards,
>Chris

**Comment by gasteve** [comment]
This project has not been abandoned.  We will prioritize getting these contributions merged.

**Comment by carnesen** [comment]
@gasteve Thanks for the reply. I'm glad to hear it! I'd still be happy to pitch in as a maintainer if you'd be willing to add me as an owner/collaborator on this repo. As I mentioned in my first comment on this issue, I'm a pretty hardcore software engineer (MIT educated!) very familiar with Node.js and the bitcoind RPC interface, also an overall pleasant and reasonable person. Just let me know.

Cheers, Chris
