### ISSUE TITLE
listen blocks

### ISSUE THREAD

**Issue by Chakhalyan1** [bitpay/bitcoind-rpc#32]
Hi, how can real time listen blocks with listening mempool transactions ?

**Comment by carnesen** [comment]
This library is simply a client of the bitcoin RPC interface. We'd prefer to use the issues here on this repo for bugs and feature request specific to this library. Your question is more general and as such would be better posed on other online forums such as StackOverflow. For example, this looks like a similar question though there's no answer https://bitcoin.stackexchange.com/questions/65469/how-to-get-notification-on-bitcoin-receive-with-bitcoin-core
