### ISSUE TITLE
npm registry only offers version 0.0.0, an empty repository

### ISSUE THREAD

**Issue by chrisarnesen** [bitpay/bitcoind-rpc#4]
The [npm entry for bitcoind-rpc](http://registry.npmjs.org/bitcoind-rpc/) currently offers only version 0.0.0 and its [empty repository](http://registry.npmjs.org/bitcoind-rpc/-/bitcoind-rpc-0.0.0.tgz). It needs to get updated to the latest.

**Comment by braydonf** [comment]
Published
