### ISSUE TITLE
Need add a new rpc function of importMulti

### ISSUE THREAD

**Issue by molin0000** [bitpay/bitcoind-rpc#44]
https://github.com/bitpay/bitcoind-rpc/blob/bb6ebdbf7b0eff0bc5ecfccf767e28aec745a251/lib/index.js#L220

Need add a new rpc function of importMulti at this line, like this:
importMulti: 'obj obj',

**Comment by matiu** [comment]
https://github.com/bitpay/bitcoind-rpc/pull/45

thanks!
